[package]
name = "tw" # short form for tmbu-worker
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.26"
imap = "2.4.1"
lazy_static = "1.4.0"
native-tls = "0.2.11"
regex = "1.8.4"
reqwest = { version = "0.11.18", features = ["blocking", "json"] }
